### ISSUE TITLE
Does stf file supply to write multicore info?

### ISSUE THREAD

**Issue by Cranexiao95** [sparcians/stf_lib#31]
I found a STF::TRACE_FEATURE called STF_CONTAIN_MULTI_CORE. 
But I didn't find how to write multi core info to STF file in stf_writer.

**Comment by bdutro** [comment]
That isn't a fully fleshed out part of the spec yet, and some of it will depend on what your goals are. You could, for example, write each core's trace independently if you're running some kind of multiprocessing scenario.

If you want all single trace with all cores, you'll have to insert a ProcessIDExtRecord with the relevant core ID, PID, TID info every time you switch to the instruction stream for a different core.

**Comment by bdutro** [comment]
In the second case, it would also be helpful to set `STF_CONTAIN_MULTI_CORE` in the trace header as a hint to any consumers.

**Comment by Cranexiao95** [comment]
@bdutro  Thank you for your answer. 
I want to use the second case and tried to use ProcessIDExtRecord. But there is some errors. The error message is 
`what(): !headerFinalized():Attempted to write PROCESS_ID_EXT recode outside of the header`
This is part of my code. I have tried to set ProcessIDExtRecord both before and after the initialization, but the error remains the same. Is there something wrong with the way I'm using it? 
`
stf_writer.addTraceInfo(stf: :TraceInfoRecord(stf::STF_GEN::STF_GEN_QEMU, 8,0,3, "Trace from QEMU"));
stf_writer.setISA(stf::ISA::RISCV);
stf_writer.setTraceFeature(stf: :TRACE_FEATURES: : STF CONTAIN MULTI CORE);
stf_writer.setHeaderPC(pc);
stf_writer.finalizeHeader();
**stf_writer << stf::ProcessIDExtRecord(0,0,0);**
`

**Comment by Cranexiao95** [comment]
**Update:**
I found the order of the setting. ProcessIDExtRecord should be set before setting HeaderPC.
However, when I use the following order, it reports "Attemted out of write. ISA should come before PROCESS_ID_EXT".
```
stf_writer.addTraceInfo(stf: :TraceInfoRecord(stf::STF_GEN::STF_GEN_QEMU, 8,0,3, "Trace from QEMU"));
stf_writer.setISA(stf::ISA::RISCV);
stf_writer.setTraceFeature(stf: :TRACE_FEATURES: : STF CONTAIN MULTI CORE);
stf_writer << stf::ProcessIDExtRecord(0,0,0);
stf_writer.setHeaderPC(pc);
stf_writer.finalizeHeader();
```

Then I add some print info in my code and stf_writer.cpp, a strange thing happened.
```
stf_writer.addTraceInfo(stf: :TraceInfoRecord(stf::STF_GEN::STF_GEN_QEMU, 8,0,3, "Trace from QEMU"));
stf_writer.setISA(stf::ISA::RISCV);
std::cout << "ISA set" << std::cout;
stf_writer.setTraceFeature(stf: :TRACE_FEATURES: : STF CONTAIN MULTI CORE);
std::cout << "TraceFeature set" << std::cout;
stf_writer << stf::ProcessIDExtRecord(0,0,0);
stf_writer.setHeaderPC(pc);
std::cout << "Header PC set" << std::cout;
stf_writer.finalizeHeader();
```
The result is 
![image](https://github.com/sparcians/stf_lib/assets/65606942/75fcd1c7-6645-4fb4-9a6a-733d342ddf98)
It looks like that using "stf_writer<<" will set value immediatelly. "stf_writer.set**" will be slower than that.

**Comment by bdutro** [comment]
Thanks, it looks like I forgot to implement the ProcessIDExtRecord handling properly in the STFWriter. I've pushed a branch (`dev/bdutro/process-id-ext-fixes`) that should resolve it.

With these fixes, you should be able to call `stf_writer.setHeaderProcessID(x,y,z);` to set the initial core/process/thread IDs and then use `stf_writer << stf::ProcessIDExtRecord(x,y,z)` anytime during the trace to change to a different core/process/thread.

**Comment by Cranexiao95** [comment]
Thank you very much. It is solved.

**Comment by bdutro** [comment]
Thanks, I've merged the changes to master.
