### ISSUE TITLE
stf_lib CTest regression

### ISSUE THREAD

**Issue by StanSofomoDev** [sparcians/stf_lib#38]
I would like to introduce a regression target for unit testing STF_LIB using CTest. I've opened a PR with my changes -> https://github.com/sparcians/stf_lib/pull/37.

Currently, these tests serve as a stub and do not cover the STF_LIB extensively. Additional tests can be added in the future to comprehensively validate the library's functionality and reliability.

**Comment by klingaard** [comment]
This is done, correct?

**Comment by StanSofomoDev** [comment]
Correct, https://github.com/sparcians/stf_lib/pull/37 is merged.
