### ISSUE TITLE
Supporting consecutive STF_INST_MEM_CONTENT records

### ISSUE THREAD

**Issue by bit-hack** [sparcians/stf_lib#48]
I have been hitting an issue when trying to encode memory accesses of greater than 8 bytes.

The specification says of STF_INST_MEM_CONTENT records:
```
For memory accesses with data size greater than 8 bytes, use multiple STF_INST_MEM_CONTENT records, where the first STF_INST_MEM_CONTENT record refers to the address specified in the STF_INST_MEM_ACCESS record, and subsequent STF_INST_MEM_CONTENT records refer to subsequent target addresses appropriately incremented to preserve continuity of data.
```

Trying this however, I triggered an assert in stf_lib, stf-inc/stf_inst_reader.hpp: 147 
https://github.com/sparcians/stf_lib/blob/eb394e5a3fdffcf9ad4110f962f1df5134d95b1e/stf-inc/stf_inst_reader.hpp#L147
```
                    stf_assert(desc != IntDescriptor::STF_INST_MEM_CONTENT,
                               "Saw MemContentRecord without accompanying MemAccessRecord");
```

It seems like stf_lib currently only supports a single STF_INST_MEM_CONTENT record following a STF_INST_MEM_ACCESS.

stf_lib was happy if I break larger accesses into multiple smaller (64bit or less) accesses with STF_INST_MEM_ACCESS and STF_INST_MEM_CONTENT pairs, but this doesn't correctly reflect the access being performed.

**Comment by bdutro** [comment]
Yes, this is a bug in the library. I'll start working on a fix for it.

**Comment by bdutro** [comment]
Keeping this open until I've updated stf_tools with the latest stf_lib.

**Comment by bdutro** [comment]
Ok, this should be fixed in the latest stf_tools master. Feel free to either reopen this issue or open one on stf_tools if you run into more problems with this.
